<?php

namespace app\components;

/**
 * Class Comp
 * @package app\components
 */
class Comp extends \yii\base\Component {

    public $message;
    public function init()
    {
        $this->message = 'Стандартное значение';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function show($message = ''){

        if($message) {
            $this->message = $message;
        }

        return $this->message;

    }
}